### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by a-m-s** [zsh-users/zsh-autosuggestions#253]
I currently get two test failures:

```
Failures:

  1) a wrapped widget initialized before sourcing the plugin executes the custom behavior and the built-in behavior
     Failure/Error: wait_for { session.content }.to eq('foobar')
     
       expected: "foobar"
            got: "foodar"
     
       (compared using ==)
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `block (2 levels) in handle_matcher'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `loop'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `block in handle_matcher'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `block in to'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `block in with_wait'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
     # ./spec/integrations/wrapped_widget_spec.rb:18:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:31:in `with_history'
     # ./spec/integrations/wrapped_widget_spec.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:17:in `block (2 levels) in <top (required)>'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Timeout::Error:
     #   execution expired
     #   ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:16:in `sleep'

  2) a wrapped widget initialized after sourcing the plugin executes the custom behavior and the built-in behavior
     Failure/Error: wait_for { session.content }.to eq('foobar')
     
       expected: "foobar"
            got: "foodar"
     
       (compared using ==)
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `block (2 levels) in handle_matcher'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `loop'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `block in handle_matcher'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `block in to'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `block in with_wait'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
     # ./spec/integrations/wrapped_widget_spec.rb:35:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:31:in `with_history'
     # ./spec/integrations/wrapped_widget_spec.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:17:in `block (2 levels) in <top (required)>'
     # ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Timeout::Error:
     #   execution expired
     #   ./tmphome/.gem/ruby/2.4.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:16:in `sleep'
```

This is on Arch Linux with Zsh 5.3.1.

I run the tests in a blank (fake) $HOME that contains only the necessary Ruby Gems. You can see the script in the PKGBUILD at https://aur.archlinux.org/packages/zsh-autosuggestions-git/
